### ISSUE TITLE
problem with audio stream

### ISSUE THREAD

**Issue by MrShtein** [supervergil/m3u8-to-mp4#1]
Good afternoon, great library. The video stream is fine, but for some reason there is no audio stream.

**Comment by supervergil** [comment]
> Good afternoon, great library. The video stream is fine, but for some reason there is no audio stream.

Audio stream is not available yet. I will take it into consideration in the next version.

**Comment by MrShtein** [comment]
@supervergil Well, I'm working on the same topic now, if you're wondering when I can make a pull-request

**Comment by supervergil** [comment]
@MrShtein All right, I'll merge your pull-request if you make it. Thx a lot : )
