### ISSUE TITLE
Will this work inside browser as a chrome extension?

### ISSUE THREAD

**Issue by Amila-Rukshan** [supervergil/m3u8-to-mp4#2]
I build the compiled.js file with `browserify` and run in the browser it shows the following errors,

`Uncaught (in promise) TypeError: fs.existsSync is not a function`

```
const downloadTsList = list => {
  return new Promise(async (resolve, reject) => {
    try {
      // 创建文件夹
      if (!fs.existsSync(targetPath)) {
        fs.mkdirSync(targetPath);
      }
      // 数组分片
      const splitDownloadList = list.reduce((current, next, index) => {
```

How can I get this to work?

**Comment by supervergil** [comment]
This project uses "fs" module from node env which can not work in browser env , and u may fork this project and try to replace "fs" with "browserify-fs".
